# Generated by Django 5.1.4 on 2026-07-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('url', 'Web link'), ('pdf', 'PDF document'), ('docx', 'Word document'), ('txt', 'Text file'), ('md', 'Markdown file'), ('paste', 'Pasted text')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, help_text='For link sources; also the citation source_url.', max_length=1000)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('raw_text', models.TextField(blank=True, help_text='Extracted plain text (uploads are parsed on save).')),
                ('language', models.CharField(choices=[('auto', 'Auto-detect'), ('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='auto', max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, help_text='sha256 of raw_text; skips re-embed when unchanged.', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sources are excluded from retrieval.')),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(default=list, help_text='Canonical embedding vector (list[float]).')),
                ('model', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgesource')),
            ],
            options={
                'ordering': ['source', 'order'],
                'indexes': [models.Index(fields=['source', 'order'], name='knowledge_k_source__475548_idx')],
            },
        ),
    ]
