# Generated by Django 5.1.4 on 2026-07-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='source_url',
            field=models.URLField(blank=True, help_text='Official source link (agency page) surfaced when the AI cites this scenario.'),
        ),
        migrations.CreateModel(
            name='ScenarioEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('vector', models.JSONField(default=list)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='scenarios.scenario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scenario', 'language'), name='uniq_scenario_language_embedding')],
            },
        ),
    ]
